import React from 'react';
const shopifyProducts = [
  {
    "Handle": "tagrende-fan",
    "Title": "Tagrende fan",
    "Body (HTML)": "<ul>\n<li>Crafted from 100% organic ring-spun combed cotton for a soft feel</li>\n<li>Features a medium weight of 5.5 oz/yd² (186 g/m²) enhancing its durability</li>\n<li>Ideal for DTG and embroidery customization</li>\n<li>Designed with a classic unisex fit and side seams for a better shape</li>\n</ul>",
    "Vendor": "My Store",
    "Product Category": "",
    "Type": "Print Material",
    "Tags": "",
    "Published": "true",
    "Option1 Name": "Size",
    "Option1 Value": "S",
    "Option1 Linked To": "",
    "Option2 Name": "Color",
    "Option2 Value": "Black",
    "Option2 Linked To": "",
    "Option3 Name": "",
    "Option3 Value": "",
    "Option3 Linked To": "",
    "Variant SKU": "66d6a1a0-7aa1-4f8f-895f-32aed1f7b893",
    "Variant Grams": "131.0",
    "Variant Inventory Tracker": "",
    "Variant Inventory Policy": "deny",
    "Variant Fulfillment Service": "manual",
    "Variant Price": "271.62",
    "Variant Compare At Price": "",
    "Variant Requires Shipping": "true",
    "Variant Taxable": "true",
    "Variant Barcode": "",
    "Image Src": "https://cdn.shopify.com/s/files/1/0940/6257/6003/files/f7305418-b949-41a3-8ac5-50d5ec1bb11b.webp?v=1753043434",
    "Image Position": "1",
    "Image Alt Text": "f7305418-b949-41a3-8ac5-50d5ec1bb11b",
    "Gift Card": "false",
    "SEO Title": "",
    "SEO Description": "",
    "Google Shopping / Google Product Category": "",
    "Google Shopping / Gender": "",
    "Google Shopping / Age Group": "",
    "Google Shopping / MPN": "",
    "Google Shopping / Condition": "",
    "Google Shopping / Custom Product": "",
    "Google Shopping / Custom Label 0": "",
    "Google Shopping / Custom Label 1": "",
    "Google Shopping / Custom Label 2": "",
    "Google Shopping / Custom Label 3": "",
    "Google Shopping / Custom Label 4": "",
    "Variant Image": "https://cdn.shopify.com/s/files/1/0940/6257/6003/files/f7305418-b949-41a3-8ac5-50d5ec1bb11b.webp?v=1753043434",
    "Variant Weight Unit": "g",
    "Variant Tax Code": "",
    "Cost per item": "135.81",
    "Status": "active"
  },
  {
    "Handle": "tagrende-fan",
    "Title": "",
    "Body (HTML)": "",
    "Vendor": "",
    "Product Category": "",
    "Type": "",
    "Tags": "",
    "Published": "",
    "Option1 Name": "Size",
    "Option1 Value": "S",
    "Option1 Linked To": "",
    "Option2 Name": "Color",
    "Option2 Value": "White",
    "Option2 Linked To": "",
    "Option3 Name": "",
    "Option3 Value": "",
    "Option3 Linked To": "",
    "Variant SKU": "a40aaed5-1eca-4a43-98c3-8895988a7a47",
    "Variant Grams": "131.0",
    "Variant Inventory Tracker": "",
    "Variant Inventory Policy": "deny",
    "Variant Fulfillment Service": "manual",
    "Variant Price": "271.62",
    "Variant Compare At Price": "",
    "Variant Requires Shipping": "true",
    "Variant Taxable": "true",
    "Variant Barcode": "",
    "Image Src": "https://cdn.shopify.com/s/files/1/0940/6257/6003/files/bf139ec4-9f7b-43b7-ad2f-caffdece195e.webp?v=1753043435",
    "Image Position": "2",
    "Image Alt Text": "bf139ec4-9f7b-43b7-ad2f-caffdece195e",
    "Gift Card": "",
    "SEO Title": "",
    "SEO Description": "",
    "Google Shopping / Google Product Category": "",
    "Google Shopping / Gender": "",
    "Google Shopping / Age Group": "",
    "Google Shopping / MPN": "",
    "Google Shopping / Condition": "",
    "Google Shopping / Custom Product": "",
    "Google Shopping / Custom Label 0": "",
    "Google Shopping / Custom Label 1": "",
    "Google Shopping / Custom Label 2": "",
    "Google Shopping / Custom Label 3": "",
    "Google Shopping / Custom Label 4": "",
    "Variant Image": "https://cdn.shopify.com/s/files/1/0940/6257/6003/files/bf139ec4-9f7b-43b7-ad2f-caffdece195e.webp?v=1753043435",
    "Variant Weight Unit": "g",
    "Variant Tax Code": "",
    "Cost per item": "135.81",
    "Status": ""
  },
  {
    "Handle": "tagrende-fan",
    "Title": "",
    "Body (HTML)": "",
    "Vendor": "",
    "Product Category": "",
    "Type": "",
    "Tags": "",
    "Published": "",
    "Option1 Name": "Size",
    "Option1 Value": "M",
    "Option1 Linked To": "",
    "Option2 Name": "Color",
    "Option2 Value": "Black",
    "Option2 Linked To": "",
    "Option3 Name": "",
    "Option3 Value": "",
    "Option3 Linked To": "",
    "Variant SKU": "358cd47a-e3b1-4988-baa9-a2c8d6bf2d0c",
    "Variant Grams": "146.0",
    "Variant Inventory Tracker": "",
    "Variant Inventory Policy": "deny",
    "Variant Fulfillment Service": "manual",
    "Variant Price": "271.62",
    "Variant Compare At Price": "",
    "Variant Requires Shipping": "true",
    "Variant Taxable": "true",
    "Variant Barcode": "",
    "Image Src": "https://cdn.shopify.com/s/files/1/0940/6257/6003/files/08507eec-427c-4dd5-8ea3-7a8dc3ae9a93.webp?v=1753043436",
    "Image Position": "3",
    "Image Alt Text": "08507eec-427c-4dd5-8ea3-7a8dc3ae9a93",
    "Gift Card": "",
    "SEO Title": "",
    "SEO Description": "",
    "Google Shopping / Google Product Category": "",
    "Google Shopping / Gender": "",
    "Google Shopping / Age Group": "",
    "Google Shopping / MPN": "",
    "Google Shopping / Condition": "",
    "Google Shopping / Custom Product": "",
    "Google Shopping / Custom Label 0": "",
    "Google Shopping / Custom Label 1": "",
    "Google Shopping / Custom Label 2": "",
    "Google Shopping / Custom Label 3": "",
    "Google Shopping / Custom Label 4": "",
    "Variant Image": "https://cdn.shopify.com/s/files/1/0940/6257/6003/files/f7305418-b949-41a3-8ac5-50d5ec1bb11b.webp?v=1753043434",
    "Variant Weight Unit": "g",
    "Variant Tax Code": "",
    "Cost per item": "135.81",
    "Status": ""
  },
  {
    "Handle": "tagrende-fan",
    "Title": "",
    "Body (HTML)": "",
    "Vendor": "",
    "Product Category": "",
    "Type": "",
    "Tags": "",
    "Published": "",
    "Option1 Name": "Size",
    "Option1 Value": "M",
    "Option1 Linked To": "",
    "Option2 Name": "Color",
    "Option2 Value": "White",
    "Option2 Linked To": "",
    "Option3 Name": "",
    "Option3 Value": "",
    "Option3 Linked To": "",
    "Variant SKU": "daed52d5-8e8c-459a-9276-27f6c06826af",
    "Variant Grams": "146.0",
    "Variant Inventory Tracker": "",
    "Variant Inventory Policy": "deny",
    "Variant Fulfillment Service": "manual",
    "Variant Price": "271.62",
    "Variant Compare At Price": "",
    "Variant Requires Shipping": "true",
    "Variant Taxable": "true",
    "Variant Barcode": "",
    "Image Src": "https://cdn.shopify.com/s/files/1/0940/6257/6003/files/4997c4f4-f30d-420d-ba52-24d825effcc1.webp?v=1753043437",
    "Image Position": "4",
    "Image Alt Text": "4997c4f4-f30d-420d-ba52-24d825effcc1",
    "Gift Card": "",
    "SEO Title": "",
    "SEO Description": "",
    "Google Shopping / Google Product Category": "",
    "Google Shopping / Gender": "",
    "Google Shopping / Age Group": "",
    "Google Shopping / MPN": "",
    "Google Shopping / Condition": "",
    "Google Shopping / Custom Product": "",
    "Google Shopping / Custom Label 0": "",
    "Google Shopping / Custom Label 1": "",
    "Google Shopping / Custom Label 2": "",
    "Google Shopping / Custom Label 3": "",
    "Google Shopping / Custom Label 4": "",
    "Variant Image": "https://cdn.shopify.com/s/files/1/0940/6257/6003/files/08507eec-427c-4dd5-8ea3-7a8dc3ae9a93.webp?v=1753043436",
    "Variant Weight Unit": "g",
    "Variant Tax Code": "",
    "Cost per item": "135.81",
    "Status": ""
  },
  {
    "Handle": "tagrende-fan",
    "Title": "",
    "Body (HTML)": "",
    "Vendor": "",
    "Product Category": "",
    "Type": "",
    "Tags": "",
    "Published": "",
    "Option1 Name": "Size",
    "Option1 Value": "L",
    "Option1 Linked To": "",
    "Option2 Name": "Color",
    "Option2 Value": "Black",
    "Option2 Linked To": "",
    "Option3 Name": "",
    "Option3 Value": "",
    "Option3 Linked To": "",
    "Variant SKU": "20cea7ae-35e9-4365-9e0d-003e6147da64",
    "Variant Grams": "162.0",
    "Variant Inventory Tracker": "",
    "Variant Inventory Policy": "deny",
    "Variant Fulfillment Service": "manual",
    "Variant Price": "271.62",
    "Variant Compare At Price": "",
    "Variant Requires Shipping": "true",
    "Variant Taxable": "true",
    "Variant Barcode": "",
    "Image Src": "https://cdn.shopify.com/s/files/1/0940/6257/6003/files/f5cce173-f24b-42b8-9388-335f64489f2a.webp?v=1753043437",
    "Image Position": "5",
    "Image Alt Text": "f5cce173-f24b-42b8-9388-335f64489f2a",
    "Gift Card": "",
    "SEO Title": "",
    "SEO Description": "",
    "Google Shopping / Google Product Category": "",
    "Google Shopping / Gender": "",
    "Google Shopping / Age Group": "",
    "Google Shopping / MPN": "",
    "Google Shopping / Condition": "",
    "Google Shopping / Custom Product": "",
    "Google Shopping / Custom Label 0": "",
    "Google Shopping / Custom Label 1": "",
    "Google Shopping / Custom Label 2": "",
    "Google Shopping / Custom Label 3": "",
    "Google Shopping / Custom Label 4": "",
    "Variant Image": "https://cdn.shopify.com/s/files/1/0940/6257/6003/files/f7305418-b949-41a3-8ac5-50d5ec1bb11b.webp?v=1753043434",
    "Variant Weight Unit": "g",
    "Variant Tax Code": "",
    "Cost per item": "135.81",
    "Status": ""
  },
  {
    "Handle": "tagrende-fan",
    "Title": "",
    "Body (HTML)": "",
    "Vendor": "",
    "Product Category": "",
    "Type": "",
    "Tags": "",
    "Published": "",
    "Option1 Name": "Size",
    "Option1 Value": "L",
    "Option1 Linked To": "",
    "Option2 Name": "Color",
    "Option2 Value": "White",
    "Option2 Linked To": "",
    "Option3 Name": "",
    "Option3 Value": "",
    "Option3 Linked To": "",
    "Variant SKU": "5797b5f5-db48-4688-b6c2-079621ee9b98",
    "Variant Grams": "162.0",
    "Variant Inventory Tracker": "",
    "Variant Inventory Policy": "deny",
    "Variant Fulfillment Service": "manual",
    "Variant Price": "271.62",
    "Variant Compare At Price": "",
    "Variant Requires Shipping": "true",
    "Variant Taxable": "true",
    "Variant Barcode": "",
    "Image Src": "",
    "Image Position": "",
    "Image Alt Text": "",
    "Gift Card": "",
    "SEO Title": "",
    "SEO Description": "",
    "Google Shopping / Google Product Category": "",
    "Google Shopping / Gender": "",
    "Google Shopping / Age Group": "",
    "Google Shopping / MPN": "",
    "Google Shopping / Condition": "",
    "Google Shopping / Custom Product": "",
    "Google Shopping / Custom Label 0": "",
    "Google Shopping / Custom Label 1": "",
    "Google Shopping / Custom Label 2": "",
    "Google Shopping / Custom Label 3": "",
    "Google Shopping / Custom Label 4": "",
    "Variant Image": "https://cdn.shopify.com/s/files/1/0940/6257/6003/files/bf139ec4-9f7b-43b7-ad2f-caffdece195e.webp?v=1753043435",
    "Variant Weight Unit": "g",
    "Variant Tax Code": "",
    "Cost per item": "135.81",
    "Status": ""
  },
  {
    "Handle": "tagrende-fan",
    "Title": "",
    "Body (HTML)": "",
    "Vendor": "",
    "Product Category": "",
    "Type": "",
    "Tags": "",
    "Published": "",
    "Option1 Name": "Size",
    "Option1 Value": "XL",
    "Option1 Linked To": "",
    "Option2 Name": "Color",
    "Option2 Value": "Black",
    "Option2 Linked To": "",
    "Option3 Name": "",
    "Option3 Value": "",
    "Option3 Linked To": "",
    "Variant SKU": "a2095a5f-b2d0-49f4-8b05-a6f7f653cea1",
    "Variant Grams": "190.0",
    "Variant Inventory Tracker": "",
    "Variant Inventory Policy": "deny",
    "Variant Fulfillment Service": "manual",
    "Variant Price": "271.62",
    "Variant Compare At Price": "",
    "Variant Requires Shipping": "true",
    "Variant Taxable": "true",
    "Variant Barcode": "",
    "Image Src": "",
    "Image Position": "",
    "Image Alt Text": "",
    "Gift Card": "",
    "SEO Title": "",
    "SEO Description": "",
    "Google Shopping / Google Product Category": "",
    "Google Shopping / Gender": "",
    "Google Shopping / Age Group": "",
    "Google Shopping / MPN": "",
    "Google Shopping / Condition": "",
    "Google Shopping / Custom Product": "",
    "Google Shopping / Custom Label 0": "",
    "Google Shopping / Custom Label 1": "",
    "Google Shopping / Custom Label 2": "",
    "Google Shopping / Custom Label 3": "",
    "Google Shopping / Custom Label 4": "",
    "Variant Image": "https://cdn.shopify.com/s/files/1/0940/6257/6003/files/f7305418-b949-41a3-8ac5-50d5ec1bb11b.webp?v=1753043434",
    "Variant Weight Unit": "g",
    "Variant Tax Code": "",
    "Cost per item": "135.81",
    "Status": ""
  },
  {
    "Handle": "tagrende-fan",
    "Title": "",
    "Body (HTML)": "",
    "Vendor": "",
    "Product Category": "",
    "Type": "",
    "Tags": "",
    "Published": "",
    "Option1 Name": "Size",
    "Option1 Value": "XL",
    "Option1 Linked To": "",
    "Option2 Name": "Color",
    "Option2 Value": "White",
    "Option2 Linked To": "",
    "Option3 Name": "",
    "Option3 Value": "",
    "Option3 Linked To": "",
    "Variant SKU": "177f2acd-72be-4c95-bbec-7a4a8ec0f798",
    "Variant Grams": "190.0",
    "Variant Inventory Tracker": "",
    "Variant Inventory Policy": "deny",
    "Variant Fulfillment Service": "manual",
    "Variant Price": "271.62",
    "Variant Compare At Price": "",
    "Variant Requires Shipping": "true",
    "Variant Taxable": "true",
    "Variant Barcode": "",
    "Image Src": "",
    "Image Position": "",
    "Image Alt Text": "",
    "Gift Card": "",
    "SEO Title": "",
    "SEO Description": "",
    "Google Shopping / Google Product Category": "",
    "Google Shopping / Gender": "",
    "Google Shopping / Age Group": "",
    "Google Shopping / MPN": "",
    "Google Shopping / Condition": "",
    "Google Shopping / Custom Product": "",
    "Google Shopping / Custom Label 0": "",
    "Google Shopping / Custom Label 1": "",
    "Google Shopping / Custom Label 2": "",
    "Google Shopping / Custom Label 3": "",
    "Google Shopping / Custom Label 4": "",
    "Variant Image": "https://cdn.shopify.com/s/files/1/0940/6257/6003/files/bf139ec4-9f7b-43b7-ad2f-caffdece195e.webp?v=1753043435",
    "Variant Weight Unit": "g",
    "Variant Tax Code": "",
    "Cost per item": "135.81",
    "Status": ""
  },
  {
    "Handle": "tagrende-fan",
    "Title": "",
    "Body (HTML)": "",
    "Vendor": "",
    "Product Category": "",
    "Type": "",
    "Tags": "",
    "Published": "",
    "Option1 Name": "Size",
    "Option1 Value": "2XL",
    "Option1 Linked To": "",
    "Option2 Name": "Color",
    "Option2 Value": "Black",
    "Option2 Linked To": "",
    "Option3 Name": "",
    "Option3 Value": "",
    "Option3 Linked To": "",
    "Variant SKU": "a301a512-c8f7-4d3f-9ba6-4ca28fe56434",
    "Variant Grams": "206.0",
    "Variant Inventory Tracker": "",
    "Variant Inventory Policy": "deny",
    "Variant Fulfillment Service": "manual",
    "Variant Price": "300.14",
    "Variant Compare At Price": "",
    "Variant Requires Shipping": "true",
    "Variant Taxable": "true",
    "Variant Barcode": "",
    "Image Src": "",
    "Image Position": "",
    "Image Alt Text": "",
    "Gift Card": "",
    "SEO Title": "",
    "SEO Description": "",
    "Google Shopping / Google Product Category": "",
    "Google Shopping / Gender": "",
    "Google Shopping / Age Group": "",
    "Google Shopping / MPN": "",
    "Google Shopping / Condition": "",
    "Google Shopping / Custom Product": "",
    "Google Shopping / Custom Label 0": "",
    "Google Shopping / Custom Label 1": "",
    "Google Shopping / Custom Label 2": "",
    "Google Shopping / Custom Label 3": "",
    "Google Shopping / Custom Label 4": "",
    "Variant Image": "https://cdn.shopify.com/s/files/1/0940/6257/6003/files/f7305418-b949-41a3-8ac5-50d5ec1bb11b.webp?v=1753043434",
    "Variant Weight Unit": "g",
    "Variant Tax Code": "",
    "Cost per item": "150.07",
    "Status": ""
  },
  {
    "Handle": "tagrende-fan",
    "Title": "",
    "Body (HTML)": "",
    "Vendor": "",
    "Product Category": "",
    "Type": "",
    "Tags": "",
    "Published": "",
    "Option1 Name": "Size",
    "Option1 Value": "2XL",
    "Option1 Linked To": "",
    "Option2 Name": "Color",
    "Option2 Value": "White",
    "Option2 Linked To": "",
    "Option3 Name": "",
    "Option3 Value": "",
    "Option3 Linked To": "",
    "Variant SKU": "a1f30cd5-af85-4ff2-8edf-21117ed908c2",
    "Variant Grams": "206.0",
    "Variant Inventory Tracker": "",
    "Variant Inventory Policy": "deny",
    "Variant Fulfillment Service": "manual",
    "Variant Price": "300.14",
    "Variant Compare At Price": "",
    "Variant Requires Shipping": "true",
    "Variant Taxable": "true",
    "Variant Barcode": "",
    "Image Src": "",
    "Image Position": "",
    "Image Alt Text": "",
    "Gift Card": "",
    "SEO Title": "",
    "SEO Description": "",
    "Google Shopping / Google Product Category": "",
    "Google Shopping / Gender": "",
    "Google Shopping / Age Group": "",
    "Google Shopping / MPN": "",
    "Google Shopping / Condition": "",
    "Google Shopping / Custom Product": "",
    "Google Shopping / Custom Label 0": "",
    "Google Shopping / Custom Label 1": "",
    "Google Shopping / Custom Label 2": "",
    "Google Shopping / Custom Label 3": "",
    "Google Shopping / Custom Label 4": "",
    "Variant Image": "https://cdn.shopify.com/s/files/1/0940/6257/6003/files/bf139ec4-9f7b-43b7-ad2f-caffdece195e.webp?v=1753043435",
    "Variant Weight Unit": "g",
    "Variant Tax Code": "",
    "Cost per item": "150.07",
    "Status": ""
  }
];

export const getShopifyProducts = () => {
  const productsByHandle = {};

  shopifyProducts.forEach(row => {
    if (!row.Handle) return;
    if (!productsByHandle[row.Handle]) {
      productsByHandle[row.Handle] = {
        id: row.Handle,
        name: row.Title,
        description: row['Body (HTML)'],
        variants: [],
        images: []
      };
    }

    const product = productsByHandle[row.Handle];

    if (row.Title) product.name = row.Title;
    if (row['Body (HTML)']) product.description = row['Body (HTML)'];

    product.variants.push({
      sku: row['Variant SKU'],
      price: parseFloat(row['Variant Price']),
      size: row['Option1 Value'],
      color: row['Option2 Value'],
      image: row['Variant Image']
    });

    if (row['Image Src'] && !product.images.some(img => img.src === row['Image Src'])) {
      product.images.push({
        src: row['Image Src'],
        alt: row['Image Alt Text'],
        position: parseInt(row['Image Position'], 10)
      });
    }
  });

  return Object.values(productsByHandle).map(product => {
    product.images.sort((a, b) => a.position - b.position);
    return product;
  });
};
