export const shopifyProducts = [
  {
    "Handle": "tagrende-fan",
    "Title": "Tagrende Fan Tee",
    "Body (HTML)": "<ul>\\n<li>Crafted from 100% organic ring-spun combed cotton for a soft feel</li>\\n<li>Features a medium weight of 5.5 oz/yd² (186 g/m²) enhancing its durability</li>\\n<li>Ideal for DTG and embroidery customization</li>\\n<li>Designed with a classic unisex fit and side seams for a better shape</li>\\n</ul>",
    "Vendor": "My Store",
    "Product Category": "",
    "Type": "Print Material",
    "Tags": "",
    "Published": "true",
    "Option1 Name": "Size",
    "Option1 Value": "S",
    "Option1 Linked To": "",
    "Option2 Name": "Color",
    "Option2 Value": "Black",
    "Option2 Linked To": "",
    "Option3 Name": "",
    "Option3 Value": "",
    "Option3 Linked To": "",
    "Variant SKU": "Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0LzE1MzA2MjEzNzIwNDUx",
    "Variant Grams": "131.0",
    "Variant Inventory Tracker": "",
    "Variant Inventory Policy": "deny",
    "Variant Fulfillment Service": "manual",
    "Variant Price": "271.62",
    "Variant Compare At Price": "",
    "Variant Requires Shipping": "true",
    "Variant Taxable": "true",
    "Variant Barcode": "",
    "Image Src": "https://cdn.shopify.com/s/files/1/0940/6257/6003/files/f7305418-b949-41a3-8ac5-50d5ec1bb11b.webp?v=1753043434",
    "Image Position": "1",
    "Image Alt Text": "Black Tagrende Fan Tee",
    "Gift Card": "false",
    "SEO Title": "",
    "SEO Description": "",
    "Google Shopping / Google Product Category": "",
    "Google Shopping / Gender": "",
    "Google Shopping / Age Group": "",
    "Google Shopping / MPN": "",
    "Google Shopping / Condition": "",
    "Google Shopping / Custom Product": "",
    "Google Shopping / Custom Label 0": "",
    "Google Shopping / Custom Label 1": "",
    "Google Shopping / Custom Label 2": "",
    "Google Shopping / Custom Label 3": "",
    "Google Shopping / Custom Label 4": "",
    "Variant Image": "https://cdn.shopify.com/s/files/1/0940/6257/6003/files/f7305418-b949-41a3-8ac5-50d5ec1bb11b.webp?v=1753043434",
    "Variant Weight Unit": "g",
    "Variant Tax Code": "",
    "Cost per item": "135.81",
    "Status": "active"
  },
  {
    "Handle": "tagrende-fan",
    "Title": "",
    "Body (HTML)": "",
    "Vendor": "",
    "Product Category": "",
    "Type": "",
    "Tags": "",
    "Published": "",
    "Option1 Name": "Size",
    "Option1 Value": "S",
    "Option1 Linked To": "",
    "Option2 Name": "Color",
    "Option2 Value": "White",
    "Option2 Linked To": "",
    "Option3 Name": "",
    "Option3 Value": "",
    "Option3 Linked To": "",
    "Variant SKU": "",
    "Variant Grams": "131.0",
    "Variant Inventory Tracker": "",
    "Variant Inventory Policy": "deny",
    "Variant Fulfillment Service": "manual",
    "Variant Price": "271.62",
    "Variant Compare At Price": "",
    "Variant Requires Shipping": "true",
    "Variant Taxable": "true",
    "Variant Barcode": "",
    "Image Src": "https://cdn.shopify.com/s/files/1/0940/6257/6003/files/bf139ec4-9f7b-43b7-ad2f-caffdece195e.webp?v=1753043435",
    "Image Position": "2",
    "Image Alt Text": "White Tagrende Fan Tee",
    "Gift Card": "",
    "SEO Title": "",
    "SEO Description": "",
    "Google Shopping / Google Product Category": "",
    "Google Shopping / Gender": "",
    "Google Shopping / Age Group": "",
    "Google Shopping / MPN": "",
    "Google Shopping / Condition": "",
    "Google Shopping / Custom Product": "",
    "Google Shopping / Custom Label 0": "",
    "Google Shopping / Custom Label 1": "",
    "Google Shopping / Custom Label 2": "",
    "Google Shopping / Custom Label 3": "",
    "Google Shopping / Custom Label 4": "",
    "Variant Image": "https://cdn.shopify.com/s/files/1/0940/6257/6003/files/bf139ec4-9f7b-43b7-ad2f-caffdece195e.webp?v=1753043435",
    "Variant Weight Unit": "g",
    "Variant Tax Code": "",
    "Cost per item": "135.81",
    "Status": ""
  },
  {
    "Handle": "tagrende-fan",
    "Title": "",
    "Body (HTML)": "",
    "Vendor": "",
    "Product Category": "",
    "Type": "",
    "Tags": "",
    "Published": "",
    "Option1 Name": "Size",
    "Option1 Value": "M",
    "Option1 Linked To": "",
    "Option2 Name": "Color",
    "Option2 Value": "Black",
    "Option2 Linked To": "",
    "Option3 Name": "",
    "Option3 Value": "",
    "Option3 Linked To": "",
    "Variant SKU": "",
    "Variant Grams": "146.0",
    "Variant Inventory Tracker": "",
    "Variant Inventory Policy": "deny",
    "Variant Fulfillment Service": "manual",
    "Variant Price": "271.62",
    "Variant Compare At Price": "",
    "Variant Requires Shipping": "true",
    "Variant Taxable": "true",
    "Variant Barcode": "",
    "Image Src": "",
    "Image Position": "",
    "Image Alt Text": "",
    "Gift Card": "",
    "SEO Title": "",
    "SEO Description": "",
    "Google Shopping / Google Product Category": "",
    "Google Shopping / Gender": "",
    "Google Shopping / Age Group": "",
    "Google Shopping / MPN": "",
    "Google Shopping / Condition": "",
    "Google Shopping / Custom Product": "",
    "Google Shopping / Custom Label 0": "",
    "Google Shopping / Custom Label 1": "",
    "Google Shopping / Custom Label 2": "",
    "Google Shopping / Custom Label 3": "",
    "Google Shopping / Custom Label 4": "",
    "Variant Image": "https://cdn.shopify.com/s/files/1/0940/6257/6003/files/f7305418-b949-41a3-8ac5-50d5ec1bb11b.webp?v=1753043434",
    "Variant Weight Unit": "g",
    "Variant Tax Code": "",
    "Cost per item": "135.81",
    "Status": ""
  },
  {
    "Handle": "tagrende-fan",
    "Title": "",
    "Body (HTML)": "",
    "Vendor": "",
    "Product Category": "",
    "Type": "",
    "Tags": "",
    "Published": "",
    "Option1 Name": "Size",
    "Option1 Value": "M",
    "Option1 Linked To": "",
    "Option2 Name": "Color",
    "Option2 Value": "White",
    "Option2 Linked To": "",
    "Option3 Name": "",
    "Option3 Value": "",
    "Option3 Linked To": "",
    "Variant SKU": "",
    "Variant Grams": "146.0",
    "Variant Inventory Tracker": "",
    "Variant Inventory Policy": "deny",
    "Variant Fulfillment Service": "manual",
    "Variant Price": "271.62",
    "Variant Compare At Price": "",
    "Variant Requires Shipping": "true",
    "Variant Taxable": "true",
    "Variant Barcode": "",
    "Image Src": "",
    "Image Position": "",
    "Image Alt Text": "",
    "Gift Card": "",
    "SEO Title": "",
    "SEO Description": "",
    "Google Shopping / Google Product Category": "",
    "Google Shopping / Gender": "",
    "Google Shopping / Age Group": "",
    "Google Shopping / MPN": "",
    "Google Shopping / Condition": "",
    "Google Shopping / Custom Product": "",
    "Google Shopping / Custom Label 0": "",
    "Google Shopping / Custom Label 1": "",
    "Google Shopping / Custom Label 2": "",
    "Google Shopping / Custom Label 3": "",
    "Google Shopping / Custom Label 4": "",
    "Variant Image": "https://cdn.shopify.com/s/files/1/0940/6257/6003/files/bf139ec4-9f7b-43b7-ad2f-caffdece195e.webp?v=1753043435",
    "Variant Weight Unit": "g",
    "Variant Tax Code": "",
    "Cost per item": "135.81",
    "Status": ""
  },
  {
    "Handle": "tagrende-fan",
    "Title": "",
    "Body (HTML)": "",
    "Vendor": "",
    "Product Category": "",
    "Type": "",
    "Tags": "",
    "Published": "",
    "Option1 Name": "Size",
    "Option1 Value": "L",
    "Option1 Linked To": "",
    "Option2 Name": "Color",
    "Option2 Value": "Black",
    "Option2 Linked To": "",
    "Option3 Name": "",
    "Option3 Value": "",
    "Option3 Linked To": "",
    "Variant SKU": "",
    "Variant Grams": "162.0",
    "Variant Inventory Tracker": "",
    "Variant Inventory Policy": "deny",
    "Variant Fulfillment Service": "manual",
    "Variant Price": "271.62",
    "Variant Compare At Price": "",
    "Variant Requires Shipping": "true",
    "Variant Taxable": "true",
    "Variant Barcode": "",
    "Image Src": "",
    "Image Position": "",
    "Image Alt Text": "",
    "Gift Card": "",
    "SEO Title": "",
    "SEO Description": "",
    "Google Shopping / Google Product Category": "",
    "Google Shopping / Gender": "",
    "Google Shopping / Age Group": "",
    "Google Shopping / MPN": "",
    "Google Shopping / Condition": "",
    "Google Shopping / Custom Product": "",
    "Google Shopping / Custom Label 0": "",
    "Google Shopping / Custom Label 1": "",
    "Google Shopping / Custom Label 2": "",
    "Google Shopping / Custom Label 3": "",
    "Google Shopping / Custom Label 4": "",
    "Variant Image": "https://cdn.shopify.com/s/files/1/0940/6257/6003/files/f7305418-b949-41a3-8ac5-50d5ec1bb11b.webp?v=1753043434",
    "Variant Weight Unit": "g",
    "Variant Tax Code": "",
    "Cost per item": "135.81",
    "Status": ""
  },
  {
    "Handle": "tagrende-fan",
    "Title": "",
    "Body (HTML)": "",
    "Vendor": "",
    "Product Category": "",
    "Type": "",
    "Tags": "",
    "Published": "",
    "Option1 Name": "Size",
    "Option1 Value": "L",
    "Option1 Linked To": "",
    "Option2 Name": "Color",
    "Option2 Value": "White",
    "Option2 Linked To": "",
    "Option3 Name": "",
    "Option3 Value": "",
    "Option3 Linked To": "",
    "Variant SKU": "",
    "Variant Grams": "162.0",
    "Variant Inventory Tracker": "",
    "Variant Inventory Policy": "deny",
    "Variant Fulfillment Service": "manual",
    "Variant Price": "271.62",
    "Variant Compare At Price": "",
    "Variant Requires Shipping": "true",
    "Variant Taxable": "true",
    "Variant Barcode": "",
    "Image Src": "",
    "Image Position": "",
    "Image Alt Text": "",
    "Gift Card": "",
    "SEO Title": "",
    "SEO Description": "",
    "Google Shopping / Google Product Category": "",
    "Google Shopping / Gender": "",
    "Google Shopping / Age Group": "",
    "Google Shopping / MPN": "",
    "Google Shopping / Condition": "",
    "Google Shopping / Custom Product": "",
    "Google Shopping / Custom Label 0": "",
    "Google Shopping / Custom Label 1": "",
    "Google Shopping / Custom Label 2": "",
    "Google Shopping / Custom Label 3": "",
    "Google Shopping / Custom Label 4": "",
    "Variant Image": "https://cdn.shopify.com/s/files/1/0940/6257/6003/files/bf139ec4-9f7b-43b7-ad2f-caffdece195e.webp?v=1753043435",
    "Variant Weight Unit": "g",
    "Variant Tax Code": "",
    "Cost per item": "135.81",
    "Status": ""
  },
  {
    "Handle": "tagrende-fan",
    "Title": "",
    "Body (HTML)": "",
    "Vendor": "",
    "Product Category": "",
    "Type": "",
    "Tags": "",
    "Published": "",
    "Option1 Name": "Size",
    "Option1 Value": "XL",
    "Option1 Linked To": "",
    "Option2 Name": "Color",
    "Option2 Value": "Black",
    "Option2 Linked To": "",
    "Option3 Name": "",
    "Option3 Value": "",
    "Option3 Linked To": "",
    "Variant SKU": "",
    "Variant Grams": "190.0",
    "Variant Inventory Tracker": "",
    "Variant Inventory Policy": "deny",
    "Variant Fulfillment Service": "manual",
    "Variant Price": "271.62",
    "Variant Compare At Price": "",
    "Variant Requires Shipping": "true",
    "Variant Taxable": "true",
    "Variant Barcode": "",
    "Image Src": "",
    "Image Position": "",
    "Image Alt Text": "",
    "Gift Card": "",
    "SEO Title": "",
    "SEO Description": "",
    "Google Shopping / Google Product Category": "",
    "Google Shopping / Gender": "",
    "Google Shopping / Age Group": "",
    "Google Shopping / MPN": "",
    "Google Shopping / Condition": "",
    "Google Shopping / Custom Product": "",
    "Google Shopping / Custom Label 0": "",
    "Google Shopping / Custom Label 1": "",
    "Google Shopping / Custom Label 2": "",
    "Google Shopping / Custom Label 3": "",
    "Google Shopping / Custom Label 4": "",
    "Variant Image": "https://cdn.shopify.com/s/files/1/0940/6257/6003/files/f7305418-b949-41a3-8ac5-50d5ec1bb11b.webp?v=1753043434",
    "Variant Weight Unit": "g",
    "Variant Tax Code": "",
    "Cost per item": "135.81",
    "Status": ""
  },
  {
    "Handle": "tagrende-fan",
    "Title": "",
    "Body (HTML)": "",
    "Vendor": "",
    "Product Category": "",
    "Type": "",
    "Tags": "",
    "Published": "",
    "Option1 Name": "Size",
    "Option1 Value": "XL",
    "Option1 Linked To": "",
    "Option2 Name": "Color",
    "Option2 Value": "White",
    "Option2 Linked To": "",
    "Option3 Name": "",
    "Option3 Value": "",
    "Option3 Linked To": "",
    "Variant SKU": "",
    "Variant Grams": "190.0",
    "Variant Inventory Tracker": "",
    "Variant Inventory Policy": "deny",
    "Variant Fulfillment Service": "manual",
    "Variant Price": "271.62",
    "Variant Compare At Price": "",
    "Variant Requires Shipping": "true",
    "Variant Taxable": "true",
    "Variant Barcode": "",
    "Image Src": "",
    "Image Position": "",
    "Image Alt Text": "",
    "Gift Card": "",
    "SEO Title": "",
    "SEO Description": "",
    "Google Shopping / Google Product Category": "",
    "Google Shopping / Gender": "",
    "Google Shopping / Age Group": "",
    "Google Shopping / MPN": "",
    "Google Shopping / Condition": "",
    "Google Shopping / Custom Product": "",
    "Google Shopping / Custom Label 0": "",
    "Google Shopping / Custom Label 1": "",
    "Google Shopping / Custom Label 2": "",
    "Google Shopping / Custom Label 3": "",
    "Google Shopping / Custom Label 4": "",
    "Variant Image": "https://cdn.shopify.com/s/files/1/0940/6257/6003/files/bf139ec4-9f7b-43b7-ad2f-caffdece195e.webp?v=1753043435",
    "Variant Weight Unit": "g",
    "Variant Tax Code": "",
    "Cost per item": "135.81",
    "Status": ""
  },
  {
    "Handle": "tagrende-fan",
    "Title": "",
    "Body (HTML)": "",
    "Vendor": "",
    "Product Category": "",
    "Type": "",
    "Tags": "",
    "Published": "",
    "Option1 Name": "Size",
    "Option1 Value": "2XL",
    "Option1 Linked To": "",
    "Option2 Name": "Color",
    "Option2 Value": "Black",
    "Option2 Linked To": "",
    "Option3 Name": "",
    "Option3 Value": "",
    "Option3 Linked To": "",
    "Variant SKU": "",
    "Variant Grams": "206.0",
    "Variant Inventory Tracker": "",
    "Variant Inventory Policy": "deny",
    "Variant Fulfillment Service": "manual",
    "Variant Price": "300.14",
    "Variant Compare At Price": "",
    "Variant Requires Shipping": "true",
    "Variant Taxable": "true",
    "Variant Barcode": "",
    "Image Src": "",
    "Image Position": "",
    "Image Alt Text": "",
    "Gift Card": "",
    "SEO Title": "",
    "SEO Description": "",
    "Google Shopping / Google Product Category": "",
    "Google Shopping / Gender": "",
    "Google Shopping / Age Group": "",
    "Google Shopping / MPN": "",
    "Google Shopping / Condition": "",
    "Google Shopping / Custom Product": "",
    "Google Shopping / Custom Label 0": "",
    "Google Shopping / Custom Label 1": "",
    "Google Shopping / Custom Label 2": "",
    "Google Shopping / Custom Label 3": "",
    "Google Shopping / Custom Label 4": "",
    "Variant Image": "https://cdn.shopify.com/s/files/1/0940/6257/6003/files/f7305418-b949-41a3-8ac5-50d5ec1bb11b.webp?v=1753043434",
    "Variant Weight Unit": "g",
    "Variant Tax Code": "",
    "Cost per item": "150.07",
    "Status": ""
  },
  {
    "Handle": "tagrende-fan",
    "Title": "",
    "Body (HTML)": "",
    "Vendor": "",
    "Product Category": "",
    "Type": "",
    "Tags": "",
    "Published": "",
    "Option1 Name": "Size",
    "Option1 Value": "2XL",
    "Option1 Linked To": "",
    "Option2 Name": "Color",
    "Option2 Value": "White",
    "Option2 Linked To": "",
    "Option3 Name": "",
    "Option3 Value": "",
    "Option3 Linked To": "",
    "Variant SKU": "",
    "Variant Grams": "206.0",
    "Variant Inventory Tracker": "",
    "Variant Inventory Policy": "deny",
    "Variant Fulfillment Service": "manual",
    "Variant Price": "300.14",
    "Variant Compare At Price": "",
    "Variant Requires Shipping": "true",
    "Variant Taxable": "true",
    "Variant Barcode": "",
    "Image Src": "",
    "Image Position": "",
    "Image Alt Text": "",
    "Gift Card": "",
    "SEO Title": "",
    "SEO Description": "",
    "Google Shopping / Google Product Category": "",
    "Google Shopping / Gender": "",
    "Google Shopping / Age Group": "",
    "Google Shopping / MPN": "",
    "Google Shopping / Condition": "",
    "Google Shopping / Custom Product": "",
    "Google Shopping / Custom Label 0": "",
    "Google Shopping / Custom Label 1": "",
    "Google Shopping / Custom Label 2": "",
    "Google Shopping / Custom Label 3": "",
    "Google Shopping / Custom Label 4": "",
    "Variant Image": "https://cdn.shopify.com/s/files/1/0940/6257/6003/files/bf139ec4-9f7b-43b7-ad2f-caffdece195e.webp?v=1753043435",
    "Variant Weight Unit": "g",
    "Variant Tax Code": "",
    "Cost per item": "150.07",
    "Status": ""
  }
];